### ISSUE TITLE
Add leaderboards

### ISSUE THREAD

**Issue by mistermantas** [polargalaxymc/server#10]
[Refer to this plugin](https://www.spigotmc.org/resources/leaderheads.2079/) for what I’m looking for.

If we did have leaderboards… what would they be for? Richest people on the server? Most active?

Is this a worthwhile feature? Discuss and vote with reactions.

**Comment by owengraven** [comment]
What could be cool is to not make them personal.

Town with most people living in.
Company with the best profit.
Company with the most workers
Shop with the most different products.

I don't know how do-able this might be, but it would push people to work togheter and also encourage the making of towns/companies/shops. I also feel this will bring quicker changes in the boards. Richest player usually stays the same guy for ages.

**Comment by mistermantas** [comment]
None of that is possible, no. The guild/town population thing may be, but I have to look into that.
