### ISSUE TITLE
Add donor rank

### ISSUE THREAD

**Issue by mistermantas** [polargalaxymc/server#11]
A donor rank must be EULA-compliant and nicely integrated with the forums, Discord, and the server.

This issue is used to document the full process of adding donor ranks from the top to the bottom. Here are the current issues:

### Which platform to choose

What I won’t be using:

- BuyCraft
Too expensive
- Minecraft Market
Bad management
- my own custom solution
Might be insecure, lots of work

### Perks on the server

These are definitely going to be added:

+ [Trails](https://www.spigotmc.org/resources/supertrails.1879/)
+ [HYemotes](https://www.spigotmc.org/resources/hyemotes-great-eula-perk-animated-emotes.22407/)

I’m torn on these ones:

+ [MiniMe](https://www.spigotmc.org/resources/minime-100-eula-compliant-customization-unique-donator-perk.24859/)

### Perks elsewhere

+ Special Discord role with VIP chat
+ Special role on the forums

**Comment by owengraven** [comment]
I don't know about platforms, but If possible i'd make atleast 2 ranks.

1 that will be low to mid price for entry, and is Permanent, something people can buy and show off loyalty.
a second that gives better perks and fun stuff, but is a monthly based payment.

What is also possible is to have a basic permanent VIP rank with extra monthly billable perks.
