### ISSUE TITLE
Add advanced spawners

### ISSUE THREAD

**Issue by mistermantas** [polargalaxymc/server#12]
Take a look at [this](https://www.spigotmc.org/resources/tieredspawners-extremely-configurable-1-7-10-1-11.32466/). We already have silk touch spawners, this would be icing on top.

Vote if I should prioritize on this.

**Comment by owengraven** [comment]
What is the use you have in mind for spawners on the server?

**Comment by mistermantas** [comment]
> What is the use you have in mind for spawners on the server?

Well, just like on any server, you need a spawner if you want more XP or loot. XP would be prioritized as mentioned in this issue: #7.
