### ISSUE TITLE
Publish new branding guide

### ISSUE THREAD

**Issue by mistermantas** [polargalaxymc/server#14]
# Polar Galaxy Brand Guide (Updated May 5)

## Basic principles

The Polar Galaxy brand is playful and does not stray away from common UI and UX principles established by [Material Design](https://material.io) or [Apple](https://developer.apple.com/ios/human-interface-guidelines/overview/design-principles/). Our aim is to design fun, engaging designs, alongside establishing a strong, confident brand.

### Polar Galaxy

In a non-stylized fashion, the server name is separated with a space and generally written normally like this: “Polar Galaxy”.

When the logo is stylized—for example, in game—it should be:

+ all uppercase
+ bold for “Polar”
+ not have spaces
+ be in Raleway

If Raleway is not available, the closest matching font is chosen.

### URIs (links)

When creating announcements, this is the general rule of format for good-looking URIs:

Correct: www.polargalaxy.com
Correct: forums.polargalaxy.com
Correct: www.polargalaxy.com/beta
Acceptable: polargalaxy.com
Acceptable: polargalaxy.com/beta

Wrong: http://polargalaxy.com
Wrong: https://www.polargalaxy.com
Wrong: polargalaxy.com/

URIs should:

+ only contain the domain name and the TLD
+ never include the `http` prefixe
+ never include the slash if not needed

## Colors

Our color palette is vibrant, legible, and well-suited for modern web design.

Our main brand color is a soft blue `#14B0CC` signifying ice, and cold enviroments, which relate to the name of our brand (Polar Galaxy).

## Typography

[Smart or curly quotes](https://smartquotesforsmartpoeple.com) should be used at all times with the exception of our Minecraft game server. If you cannot use such quotes in an official document, simply do not make contractions. This is usually done in formal documents anyway.

The main typeface for our brand—body and display text—is Roboto. For the logo, Raleway and the *light* (300) and *heavy* (900) weights have been chosen.

If Roboto is not available, these are the following fallbacks:

+ San Francisco
+ Segoe UI
+ Helvetica Neue
+ Helvetica
+ Arial
+ Liberation Sans
+ any sans serif typeface

If Raleway is not available, the closest matching font is chosen.

## Mascot

Our favicon and mascot is a polar bear named Happle. Happle was made by [Zyrille Sespeñe](http://zyrl.space), a freelance designer from the Phillipines, who was formerly a manager here at Polar Galaxy and part of our team.

## Disclaimer

© 2016–2017 Polar Galaxy.
All rights reserved.

**Comment by mistermantas** [comment]
Up until this point, we’ve had a branding kit of sorts. It included a basic color palette, the fonts we used, our text logo, and mascot: Happle. We’re making some changes to the kit, which should hopefully make our brand easier to understand and correctly use.

Please review the current draft and +1 this issue if you feel it is appriopriate and can be uploaded on our website.

**Comment by brandonbelisle** [comment]
Looks good, closing ticket.
