### ISSUE TITLE
Setup automatic compiling of Spigot

### ISSUE THREAD

**Issue by mistermantas** [polargalaxymc/server#18]
Every so often, when your old build expires, it can delay restarts by about 15 seconds, not to mention the fact that build updates usually contain bug fixes and such.

**Comment by brandonbelisle** [comment]
Multicraft monitors Spigot versions and will download current versions of Spigot on release. It will also do this with bungee by default.

**Comment by mistermantas** [comment]
That’s lovely.

**Comment by mistermantas** [comment]
Since we’re no longer using Multicraft, this is an issue again, isn’t it?

**Comment by mistermantas** [comment]
This could pose some problems for the future because of faulty updates, so ditching this idea.
