### ISSUE TITLE
Make mini blocks available to all players

### ISSUE THREAD

**Issue by mistermantas** [polargalaxymc/server#2]
Better known as skulls or heads, these things are accessible to staff and builders, but they’d be immensely useful for players who haven’t got an official badge.

They can be treasured like saddles, earned at a specific rank, or go on sale for everyone at spawn.

[Vote here](http://poll.lab.io/1ZK3oLVL5ntKCDCCPZ8I-g)

**Comment by temyy** [comment]
an electronics store selling toaster heads tv heads etc



_bad idea_
