### ISSUE TITLE
Make XP more valuable

### ISSUE THREAD

**Issue by mistermantas** [polargalaxymc/server#7]
Achievements (as referenced in #6) give you a *lot* of experience. It’s kind of useless in Minecraft. Sure, you can use it to enchant your items, but that’s about it.

For a server like ours, much more can be done. So far I have 2 ideas:

* Exchange XP for money
* Bottle XP for later use

What more could XP be used for?

[This could work](https://www.spigotmc.org/resources/bottledexp.2815/), but the last time I tried it didn’t… for some reason.

**Comment by owengraven** [comment]
Maybe a cool idea but i don't know how you'd want it to be is to make XP like an illegal resource, like you  can earn it and have enchants but the fact of bottling it and having it on you could be illegal. 

That way there would be a bit of a black market for xp, which will in turn boost the use of spawners and might give an alternate market. 

Offcourse then you'd law enforcement but this could be a fun idea.

**Comment by mistermantas** [comment]
> black market for xp

I don’t think that’s a good idea. It’d complicate things too much.
